# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

install:
  # Show platform info
  - echo %PLATFORM%
  - ps: '[System.Environment]::OSVersion'
  
  # PATH
  - SET PATH=c:\python27;%PATH%
  - SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%
  - SET PATH=%APPDATA%\npm;%PATH%
  
  # OpenSSL
  - SET OPENSSL_CONF=C:\Utils\OpenSSL-Win32\bin\openssl.cfg
  
  # Update Node.js
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - node --version
  
  # Update NPM
  - npm install -g npm
  - npm --version
  
  # Update node-gyp
  - npm install -g node-gyp
  
  # Install dependencies & devDependencies
  - npm install --build-from-source --msvs_version=2013
  
  # Install build tools
  - npm install -g grunt-cli bower tsd@next
  - grunt --version
  - bower --version
  - tsd --version
  
  # Install bower packages
  - bower install
  - tsd reinstall || tsd reinstall

test_script:
  - npn test

# what combinations to test
environment:
  matrix:
    - nodejs_version: 0.10

platform:
  - x64

init:
  - git config --global core.autocrlf false

branches:
  except:
    - gh-pages

build: off
deploy: off
